import streamlit as st
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from utils.analysis import generate_demo_results

EXERCISE_DB = {
    "Pelvic_Drop": [
        {"name": "Single-leg Deadlift", "sets": "3x12", "rest": "60s",
         "tip": "ยืนขาเดียว ก้มตัวช้าๆ รักษาสะโพกให้ตรง",
         "difficulty": "⭐⭐⭐", "focus": "Glute Med, Hip Stability"},
        {"name": "Clamshell", "sets": "3x20", "rest": "30s",
         "tip": "นอนตะแคง งอเข่า 90° เปิดเข่าขึ้นช้าๆ",
         "difficulty": "⭐⭐", "focus": "Glute Med"},
        {"name": "Side-lying Hip Abduction", "sets": "3x15", "rest": "30s",
         "tip": "ยกขาขึ้นตรง ค้างไว้ 2 วินาที",
         "difficulty": "⭐⭐", "focus": "Glute Med, TFL"},
    ],
    "Head_Lean": [
        {"name": "Chin Tucks", "sets": "3x15", "rest": "30s",
         "tip": "ดึงคางเข้าหาลำคอ ค้าง 5 วินาที",
         "difficulty": "⭐", "focus": "Deep Neck Flexors"},
        {"name": "Wall Angels", "sets": "3x10", "rest": "30s",
         "tip": "พิงกำแพง แขนขยับขึ้นลงช้าๆ ไม่แอ่นหลัง",
         "difficulty": "⭐⭐", "focus": "Posture, Thoracic"},
    ],
    "Shoulder_Roll": [
        {"name": "Band Pull-Apart", "sets": "3x20", "rest": "30s",
         "tip": "ดึง resistance band ออกข้างๆ ช้าๆ",
         "difficulty": "⭐⭐", "focus": "Rear Deltoid, Rhomboids"},
        {"name": "Arm Swing Drill", "sets": "3x30s", "rest": "15s",
         "tip": "แกว่งแขน 90° ไม่ข้ามเส้นกลาง",
         "difficulty": "⭐", "focus": "Running Mechanics"},
    ],
    "Torso_Lean": [
        {"name": "Plank Variations", "sets": "3x45s", "rest": "30s",
         "tip": "ลำตัวตรง ไม่แอ่นสะโพก หายใจสม่ำเสมอ",
         "difficulty": "⭐⭐⭐", "focus": "Core Stability"},
        {"name": "Dead Bug", "sets": "3x10 each", "rest": "30s",
         "tip": "ลำตัวติดพื้น ยืดแขน-ขาตรงข้ามสลับกัน",
         "difficulty": "⭐⭐", "focus": "Anti-rotation Core"},
    ],
}

WEEKLY_PLAN_TEMPLATE = {
    "วันจันทร์": {"type": "💪 Strength", "color": "#FF6B35",
        "workouts": ["Glute Activation Circuit", "Single-leg Exercises", "Core Stability"]},
    "วันอังคาร": {"type": "🏃 Easy Run", "color": "#39FF14",
        "workouts": ["30 นาที Zone 2", "โฟกัสท่าทาง", "Cadence 170-175 spm"]},
    "วันพุธ": {"type": "🎯 Drills", "color": "#00F5FF",
        "workouts": ["A-Skip, B-Skip, C-Skip", "High Knees", "Butt Kicks", "Strides"]},
    "วันพฤหัส": {"type": "🔥 Tempo Run", "color": "#FF3CAC",
        "workouts": ["10 นาที Warm-up", "20 นาที Tempo", "10 นาที Cool-down"]},
    "วันศุกร์": {"type": "🧘 Recovery", "color": "#8BA7C7",
        "workouts": ["Yoga 30 นาที", "Foam Rolling", "Stretching ครบร่างกาย"]},
    "วันเสาร์": {"type": "🏆 Long Run", "color": "#FFD700",
        "workouts": ["วิ่งยาวตาม Plan", "โฟกัสท่าทาง", "Hydration ทุก 20 นาที"]},
    "วันอาทิตย์": {"type": "😴 Rest", "color": "#4A6080",
        "workouts": ["พักผ่อน", "เดินเบาๆ", "Sleep Quality"]},
}

def show():
    st.markdown("""
    <div style='padding: 1.5rem 0 1rem;'>
        <div style='font-family: Orbitron, monospace; font-size: 1.8rem; font-weight: 900;
             background: linear-gradient(90deg, #39FF14, #00F5FF);
             -webkit-background-clip: text; -webkit-text-fill-color: transparent;'>
            💪 แผนฝึก AI
        </div>
        <div style='color: #8BA7C7; font-size: 1rem; margin-top: 0.3rem;'>
            Personal Training Plan · Generated by AI Coach
        </div>
    </div>
    """, unsafe_allow_html=True)

    results = st.session_state.get("analysis_results") or generate_demo_results()

    # User profile inputs
    st.markdown("""
    <div style='font-family:Orbitron; color:#39FF14; font-size:0.9rem;
         text-transform:uppercase; margin-bottom:0.8rem; letter-spacing:0.1em;'>
        👤 ข้อมูลส่วนตัว
    </div>
    """, unsafe_allow_html=True)

    col1, col2, col3, col4 = st.columns(4)
    with col1:
        level = st.selectbox("ระดับ", ["เริ่มต้น", "กลาง", "สูง"], index=1)
    with col2:
        goal = st.selectbox("เป้าหมาย", ["5K", "10K", "Half Marathon", "Marathon"])
    with col3:
        days_per_week = st.selectbox("วันซ้อม/สัปดาห์", [3, 4, 5, 6], index=1)
    with col4:
        weeks = st.selectbox("ระยะเวลา (สัปดาห์)", [4, 8, 12, 16], index=1)

    st.markdown("<br>", unsafe_allow_html=True)

    # Targeted exercises based on weak points
    st.markdown("""
    <div style='font-family:Orbitron; color:#FF3CAC; font-size:0.9rem;
         text-transform:uppercase; margin-bottom:0.8rem; letter-spacing:0.1em;'>
        🎯 แบบฝึกแก้จุดอ่อน (AI-Selected)
    </div>
    """, unsafe_allow_html=True)

    # Determine weak points from results
    weak_points = []
    checks = [
        ("Pelvic_Drop", 4.0, "สะโพกตก"),
        ("Head_Lean", 8.0, "ศีรษะเอียง"),
        ("Shoulder_Roll", 5.0, "ไหล่แกว่ง"),
        ("Torso_Lean", 12.0, "ลำตัวเอียง"),
    ]
    for key, threshold, label in checks:
        val = results.get(key, {}).get("mean", 0) if isinstance(results.get(key), dict) else 0
        if val > threshold:
            weak_points.append(key)

    if not weak_points:
        weak_points = ["Pelvic_Drop", "Head_Lean"]

    for wp in weak_points[:3]:
        exercises = EXERCISE_DB.get(wp, [])
        if not exercises:
            continue

        wp_labels = {"Pelvic_Drop":"🍑 สะโพกตก","Head_Lean":"🎯 ศีรษะเอียง",
                     "Shoulder_Roll":"⚖️ ไหล่แกว่ง","Torso_Lean":"📐 ลำตัวเอียง"}
        st.markdown(f"""
        <div style='font-family:Orbitron; color:#00F5FF; font-size:0.8rem;
             margin: 0.8rem 0 0.4rem;'>{wp_labels.get(wp, wp)}</div>
        """, unsafe_allow_html=True)

        cols = st.columns(len(exercises))
        for i, ex in enumerate(exercises):
            with cols[i]:
                st.markdown(f"""
                <div class='metric-card'>
                    <div style='font-weight:700; color:#E8F4FD; margin-bottom:0.5rem;'>
                        {ex['name']}
                    </div>
                    <div style='display:flex; gap:0.5rem; margin-bottom:0.5rem; flex-wrap:wrap;'>
                        <span style='background:rgba(0,245,255,0.15); color:#00F5FF;
                              padding:0.15rem 0.5rem; border-radius:20px; font-size:0.75rem;'>
                            📋 {ex['sets']}
                        </span>
                        <span style='background:rgba(255,215,0,0.15); color:#FFD700;
                              padding:0.15rem 0.5rem; border-radius:20px; font-size:0.75rem;'>
                            ⏱️ {ex['rest']}
                        </span>
                    </div>
                    <div style='color:#8BA7C7; font-size:0.8rem; margin-bottom:0.4rem;
                         line-height:1.5;'>
                        💡 {ex['tip']}
                    </div>
                    <div style='color:#4A6080; font-size:0.75rem;'>
                        🎯 {ex['focus']}<br>{ex['difficulty']}
                    </div>
                </div>
                """, unsafe_allow_html=True)

    # Weekly plan
    st.markdown("""
    <div style='font-family:Orbitron; color:#FFD700; font-size:0.9rem;
         text-transform:uppercase; margin: 1.5rem 0 0.8rem; letter-spacing:0.1em;'>
        📅 แผนฝึกรายสัปดาห์
    </div>
    """, unsafe_allow_html=True)

    cols = st.columns(7)
    for i, (day, plan) in enumerate(WEEKLY_PLAN_TEMPLATE.items()):
        with cols[i]:
            is_rest = plan["type"] == "😴 Rest"
            opacity = "0.4" if is_rest else "1"
            st.markdown(f"""
            <div style='background:var(--bg-card); border:1px solid {plan["color"]}44;
                 border-radius:10px; padding:0.8rem 0.5rem; text-align:center;
                 border-top: 3px solid {plan["color"]}; opacity:{opacity};
                 min-height:200px;'>
                <div style='font-size:0.75rem; color:#8BA7C7; margin-bottom:0.3rem;'>{day}</div>
                <div style='font-size:0.85rem; color:{plan["color"]}; font-weight:700;
                     margin-bottom:0.6rem; line-height:1.3;'>{plan["type"]}</div>
            """, unsafe_allow_html=True)
            for w in plan["workouts"]:
                st.markdown(f"""
                <div style='font-size:0.7rem; color:#8BA7C7; margin-bottom:0.2rem;
                     padding:0.2rem; background:rgba(255,255,255,0.03);
                     border-radius:4px;'>{w}</div>
                """, unsafe_allow_html=True)
            st.markdown("</div>", unsafe_allow_html=True)

    # Progress tracking
    st.markdown("""
    <div style='font-family:Orbitron; color:#00F5FF; font-size:0.9rem;
         text-transform:uppercase; margin: 1.5rem 0 0.8rem; letter-spacing:0.1em;'>
        📈 เป้าหมายรายสัปดาห์
    </div>
    """, unsafe_allow_html=True)

    milestones = [
        ("สัปดาห์ 1-2", "#FF6B35", "เรียนรู้ท่าทางพื้นฐาน ลด Head Lean"),
        ("สัปดาห์ 3-4", "#FFD700", "เสริม Glute Med ลด Pelvic Drop 30%"),
        ("สัปดาห์ 5-6", "#39FF14", "เพิ่ม Cadence เป้า 170+ spm"),
        ("สัปดาห์ 7-8", "#00F5FF", "ทดสอบท่าวิ่งใหม่ วิเคราะห์ซ้ำ"),
    ]

    for week, color, goal_text in milestones:
        st.markdown(f"""
        <div style='display:flex; align-items:center; gap:1rem; padding:0.8rem 1rem;
             background:var(--bg-card); border:1px solid {color}33;
             border-left:4px solid {color}; border-radius:8px; margin-bottom:0.4rem;'>
            <div style='font-family:Orbitron; color:{color}; font-size:0.8rem; min-width:100px;'>
                {week}
            </div>
            <div style='color:#E8F4FD; font-size:0.9rem;'>{goal_text}</div>
        </div>
        """, unsafe_allow_html=True)
